baseURL = "https://danibacorro.github.io/blogdani/"
languageCode = "es"
title = "Blog de Dani"
theme = "tale"

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0

[params]
    relativeURLs = true
    canonifyURLs = true
